### ISSUE TITLE
Error on Product delete and Use Real-time Updates enabled

### ISSUE THREAD

**Issue by vmalyk** [clerkio/clerk-magento2#1]
## Preconditions

Magento 2.1.7
## Steps to reproduce

Stores > Config > Clerk 
Set Use Real-time Updates to "Yes" (By default It`s enabled in config)

## Actual result
On product delete Magento down wIth report/warning:
a:4:{i:0;s:124:"Warning: join(): Invalid arguments passed in /var/www/magento2/vendor/clerk/magento2/Model/Api.php on line 67";i:1;s:11462:"#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'join(): Invalid...', '/var/www/mage...', 67, Array)
#1 /var/www/magento2/vendor/clerk/magento2/Model/Api.php(67): join(',', '1')
#2 /var/www/magento2/vendor/clerk/magento2/Observer/ProductDeleteAfterDoneObserver.php(41): Clerk\Clerk\Model\Api->removeProduct('1')
#3 /var/www/magento2/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): Clerk\Clerk\Observer\ProductDeleteAfterDoneObserver->execute(Object(Magento\Framework\Event\Observer))

## Expected result
Product should be deleted without errors

## Notes

The issue is related with join function and removeProduct waits array instead string. Please fix method and remove join() , because We not use it with arrays at all and use only one value per product : https://github.com/clerkio/clerk-magento2/blob/master/Model/Api.php#L62

**Comment by RBech** [comment]
Hmm, yeah you're right!
Initially this was done in preparation of mass deletes so I was expecting an array of IDs, will accept your pull request
