### ISSUE TITLE
Javascript error in result.phtml

### ISSUE THREAD

**Issue by albertopriore** [clerkio/clerk-magento2#101]
In the file `view/frontend/templates/result.phtml` on the line 17 `res_len = (data?.products.length) ? data?.products.length : 0;`

Throw a js error: `Uncaught TypeError: Cannot read properties of undefined (reading 'length')`

The problem came from the data returned by the Clerk on response event which doesn't have `product` property, but instead has `product_data`. If we change that to `product_data` and than change the logic of the next condition ad line 18 we can fix the bug.

However, after making this change using `product_data`, there might be an issue with the appearance of the result list, as the "Load more" button is not displayed as in the previous version of the Clerk-magento2 module.

Is there something I'm missing in the configuration or is there something else to fix in the result.phtml file as I suggested?

**Comment by albertopriore** [comment]
Any updates?

**Comment by stubbedev** [comment]
@albertopriore 

This should do it: https://github.com/clerkio/clerk-magento2/commit/eaa825d939cb680e412fdfc96ad42471e1d61f9c

**Comment by stubbedev** [comment]
Yes I expect to push a tagged release tomorrow or Wednesday. Currently waiting for some auth changes to merge in before pushing the button.

You can also get it from the dev-master version before then.

**Comment by albertopriore** [comment]
@stubbedev I almost forgot about

> However, after making this change using product_data, there might be an issue with the appearance of the result list, as the "Load more" button is not displayed as in the previous version of the Clerk-magento2 module.

After your fix: https://github.com/clerkio/clerk-magento2/commit/eaa825d939cb680e412fdfc96ad42471e1d61f9c

Have you tested also the "Load more" button?

**Comment by stubbedev** [comment]
I made an error in that the no results was being checked to be true, rather than false. 

https://github.com/clerkio/clerk-magento2/commit/e0e72c0c2dca4843cc801563bc881113494d2537

Regarding the Load More, this is usually delivered with the design from my.clerk.io, as seen in the screenshot below:

![image](https://github.com/clerkio/clerk-magento2/assets/89036433/374df890-f7c3-4c1b-a84c-4b17d73b8e4a)

What issue are you seeing with your load more?

**Comment by albertopriore** [comment]
Ok good for https://github.com/clerkio/clerk-magento2/commit/e0e72c0c2dca4843cc801563bc881113494d2537.

The Load More button was inside the result.phtml file before:

https://github.com/clerkio/clerk-magento2/commit/0b04d6d65bf256b39e9d98333d255f82a95a1a31#diff-19ce21104e4d081f9e547ab0e76fe41e3f5a6d4424092f83c9b0bc8bdf401d41

That's why I couldn't find it anymore, I'll add it to the my.clerk.io template.
