### ISSUE TITLE
Issue after installing extension

### ISSUE THREAD

**Issue by Sharkozp** [clerkio/clerk-magento2#11]
Hello.

I have problem with this extension v2.2.* after deploying on my local or to remote environments. Frontend is broken with exception:

```
1 exception(s):
Exception #0 (InvalidArgumentException): Unable to serialize value.

Exception #0 (InvalidArgumentException): Unable to serialize value.
#0 /var/www/pinoshop.loc/public_html/vendor/magento/framework/App/PageCache/Kernel.php(153): Magento\Framework\Serialize\Serializer\Json->serialize(Array)
#1 /var/www/pinoshop.loc/public_html/vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php(96): Magento\Framework\App\PageCache\Kernel->process(Object(Magento\Framework\App\Response\Http\Interceptor))
#2 /var/www/pinoshop.loc/public_html/vendor/magento/framework/Interception/Interceptor.php(146): Magento\PageCache\Model\Controller\Result\BuiltinPlugin->afterRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Magento\Framework\View\Result\Page\Interceptor), Object(Magento\Framework\App\Response\Http\Interceptor))
#3 /var/www/pinoshop.loc/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#4 /var/www/pinoshop.loc/public_html/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(26): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#5 /var/www/pinoshop.loc/public_html/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#6 /var/www/pinoshop.loc/public_html/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#7 /var/www/pinoshop.loc/public_html/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#8 {main}
```

This exception is result that in admin section not added public and private keys

**Comment by RBech** [comment]
I can't reproduce this if it's still an issue with later release feel free to reopen

**Comment by mmenozzi** [comment]
This error could occur if you enter public and/or private key on a Magento installation and then you import the db dump from that installation to another one (for example between different environments of the same project: live, stage, dev, ecc...).

If you do so you must ensure that you have the same encryption key (in the `app/etc/env.php` file) between different environments. Otherwise the decrypted values for the private/public keys of Clerk will result in non-UTF8 characters in the HTTP response. This will cause the FPC to break because a string with non-UTF8 characters could not be encoded to JSON.

**Comment by tanolalano** [comment]
@mmenozzi 
I have a similar issue, the response get a non-UTF8 Feed, but I installed Clerk only in production environment. So clerck can't sync.
Any Thoughts?

**Comment by mmenozzi** [comment]
@tanolano, check if you have your public/private keys properly set using n98-magerun2 store:config:get command.

**Comment by tanolalano** [comment]
@mmenozzi the issue was caused by iubenda_coockie_solution magento2 module
thanks for help.
