### ISSUE TITLE
Serve scaled images

### ISSUE THREAD

**Issue by juandosil** [clerkio/clerk-magento2#17]
I am testing the Perfomance Score of my Magento 2 in development and without Clerk it is 86% in Gtmetrix but with Clerk it is 24% for two reasons, Serve scaled images and Optimize images https://gtmetrix.com/reports/www .vendetucasaenchina.com / gm31GxFJ
In my Magento 1 this does not happen to me. 
Could you check if there is a problem with your code in Magento 2?

**Comment by RBech** [comment]
Fixed in d9391638fa9603c469d9aa17b4d03203e91d90ec
