### ISSUE TITLE
main.CRITICAL: Warning: Illegal string offset 'label' in adminhtml/templates/facettitles.phtml on line 24 [] []

### ISSUE THREAD

**Issue by jorgb90** [clerkio/clerk-magento2#18]
HI,

Just installed your extension in Magento 2.2.6 and filled in the public and private key. After the save the Clerk configuration area stays white and returns the following error:

main.CRITICAL: Warning: Illegal string offset 'label' in /public_html/vendor/clerk/magento2/view/adminhtml/templates/facettitles.phtml on line 24 [] []

**Comment by alexey-p-whidegroup** [comment]
Got the same problem.

**Comment by alexey-p-whidegroup** [comment]
So, can you added changes into this template?

**Comment by jorgb90** [comment]
I just changed line 23 to 28 into

`                <td class="col-store-view">
                    <input class="input-text" id="" name="<?php echo $element->getName(); ?>[<?php echo $attribute; ?>]" value="" type="text">
                </td>
                <td class="col-store-view">
                    <input class="input-text" id="" name="<?php echo $element->getName(); ?>[<?php echo $attribute; ?>]" value="" type="text">
                </td>`

Now I can at least proceed in using the module, but I don't think it will be the correct fix ;-)

**Comment by janbuelens** [comment]
I used the following upgradeData script to fix the values for the faceted search titles:
https://gist.github.com/janbuelens/c2ecdd0c4f628382997d537ff66c51ec

**Comment by RBech** [comment]
fixed in @19371d6b482d42c0d3ee8013ab5e2ffa70a0a9a4
