### ISSUE TITLE
Out of Stock product still visible

### ISSUE THREAD

**Issue by tanolalano** [clerkio/clerk-magento2#20]
As described here, https://github.com/clerkio/clerk-magento2/pull/12
Out of stock products are not skipped and removed from Clerk, it will dispayed in sliders, email, reccom and search page.
As I correctly config Saelable product It will be ignored.

![3clerk1](https://user-images.githubusercontent.com/4384863/52164170-8317f200-26ed-11e9-9a6d-ff3c9e5e8083.png)

As out of stock is yet a product attribute or quantity I dont' understand why add extra field to my magento as described [here](https://help.clerk.io/using-clerk-io-on-magento-2/product-management/choosing-which-products-to-import-on-magento-2)

My config: 
Magento 2.2.6
PhP 7.1.22
clerk-magento2 v2.6.8  
Hope It will solve asap

------EDIT------
Forget to say that hidden Categories are displayed in search page

**Comment by CasperKN** [comment]
This should be fixed in the newer versions ;)
