### ISSUE TITLE
Not able to change product information from command

### ISSUE THREAD

**Issue by linh232323** [clerkio/clerk-magento2#22]
Magento : 2.3.2

run Magento command to create / edit product but got issue on non SERVER env

File https://github.com/clerkio/clerk-magento2/blob/master/Controller/Logger/ClerkLogger.php

Should be
`
         if(isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' && isset($_SERVER['HTTP_HOST']) && isset($_SERVER['REQUEST_URI']))
            $Metadata['uri'] = "http://".$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
        else if(isset($_SERVER['HTTP_HOST']) && isset($_SERVER['REQUEST_URI'])) {
            $Metadata['uri'] = "http://".$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
        }
`

**Comment by CasperKN** [comment]
Thanks for your issue reporting, its now fixed and in the v.2.8.0 that's released today
