### ISSUE TITLE
Products updated via API will not be sent to Clerk

### ISSUE THREAD

**Issue by unicoder88** [clerkio/clerk-magento2#24]
Currently we have events in `adminhtml` area only. When products are created and updated via REST API, e.g. `POST https://example.com/rest/all/V1/products`, Clerk will not receive any update.

Solutions:
a. either move event observers to global di.xml
b. grown up solution is indexer with update on save/update by schedule mode

I am a strong proponent of option b. because it has proven an industry standard with numerous projects we worked with. I made a PR before (https://github.com/clerkio/clerk-magento2/pull/13), however, we should simplify it and update.

But either choice will be a step forward.

Please have a look :)

**Comment by AndreaShining** [comment]
I am facing the same issue but on ProductSaveAfter observer.
Seems that getFields array is empty because it's not been initializer

(v2.8.3)

**Comment by CasperKN** [comment]
This should be fixed in the newer versions ;)
