### ISSUE TITLE
Issues withpowerstep popup and powerstep page

### ISSUE THREAD

**Issue by jesperbrejning** [clerkio/clerk-magento2#25]
We have installed version 3.0.0 in Magento 2.3.2 and are facing the following issues. There is a bug in the Javascript loading from clerk.io.

1) Powerstep popup does not load correctly on add to cart function. The powerstep popup loads at the buttom of the page in stead of as a popup window

2) Powerpage can only load one slider. IF you add more than one slider with product recommendations only the first content/design will load as a slider - the rest is loading in a grid.

**Comment by CasperKN** [comment]
This is fixed in the newer versions
