### ISSUE TITLE
Faceted Source Model not working for huge product data

### ISSUE THREAD

**Issue by AndreaShining** [clerkio/clerk-magento2#28]
Issue is for both Magento1 and Magento2

**Issue:** 
In clerk setting, Faceted Search multiselect is empty

**Problem:**
Source model is filled using clerk api "product/faceted". 
Response is huge because it loads all attributes for all products (even skus)

Here's the sourcemodel
<source_model>clerk/system_config_source_facetAttributes</source_model>

**Proposed solution:**
We should use Magento's attributes having "Use for layered in search" set to yes. (And we should add such attributes automatically into products feed)

**Comment by Kimpansen** [comment]
Attributes are collected from clerk api to ensure that the attributes used in "Faceted Search" are actually available in clerk.
if we use attributes from Magento directly we cannot guarantee that they are in sync with available attributes in clerk and hence the "Faceted Search" wil not work as ekspected.
