### ISSUE TITLE
typo in Observer/ProductSaveEntityAfterObserver.php

### ISSUE THREAD

**Issue by patrick-bigbridge** [clerkio/clerk-magento2#3]
"Trying to get property on non-object"

In Observer/ProductSaveEntityAfterObserver.php function execute, line 87

$productItem[$field] = $productItem->getData[$field];

should be

$productItem[$field] = $product->getData($field);

**Comment by RBech** [comment]
@patrick-bigbridge Right you are, thanks a lot! New release coming tommorow
