### ISSUE TITLE
Error on Powerstep popup when add to cart fails

### ISSUE THREAD

**Issue by fabianaromagnoli** [clerkio/clerk-magento2#32]
### Preconditions
* Magento 2.2.11 EE 
* PHP 7.2
* clerk-magento2 2.6.8

### Steps to reproduce
* Install clerk-magento2 2.6.8 on Magento 2.2.11 EE
* Enable powerstep popup 
* Set up a product to have stock quantity 5, and backorders not active.
* Go to the product page, and add to cart 100 pieces.

### Expected behavior
* Powerstep popup does not open (or should it open anyway?), and there are no errors server side

### Actual behavior
* Powerstep popup does not open but you get a fatal error:

> PHP Fatal error:  Uncaught Error: Call to a member function getImage() on boolean in /my/project/path/vendor/clerk/magento2/Block/PowerstepPopup.php:116

This happens because add to cart fails, event checkout_cart_add_product_complete is not dispatched, so CheckoutCartAddProductCompleteObserver in never executed, and clerkProductId is never set in checkoutSession.

**Comment by CasperKN** [comment]
This is fixed in the newer versions of the module ;)
