### ISSUE TITLE
Clerk menu not shown in stores -> configuration

### ISSUE THREAD

**Issue by dverkade** [clerkio/clerk-magento2#33]
**Description**

When I go into the stores -> configuration settings I do not see a tab anymore for Clerk.

**System environment**

- Magento 2.3.4
- Was on Clerk 3.X and upgraded to version 4 using composer.
- Executed a bin/magento setup:upgrade and cleared all cached
- Configuration tab is not shown
- I can see the added menu items under the "reports" menu.

![image](https://user-images.githubusercontent.com/1058480/77688095-cabba600-6f9f-11ea-93ee-6b4cc148dc02.png)

**Comment by unicoder88** [comment]
Took me a while to figure this out too.

Switch scope to Website, and it will show up.

**Comment by dverkade** [comment]
That's not what I would call an intuitive user interface.
