### ISSUE TITLE
Directly calling ObjectManager

### ISSUE THREAD

**Issue by JamesFX2** [clerkio/clerk-magento2#35]
Hi,

I've noticed that you're directly calling the Object Manager. Magento says that developers should not use the object manager directly to load classes, instead inject the object in the constructors.

See

app/code/Clerk/Clerk/Model/Adapter/Product.php
app/code/Clerk/Clerk/Model/Config/Source/Language.php
app/code/Clerk/Clerk/Controller/Logger/ClerkLogger.php
app/code/Clerk/Clerk/Controller/Product/Index.php
app/code/Clerk/Clerk/Controller/AbstractAction.php
app/code/Clerk/Clerk/Controller/Version/Index.php

Can you look at this and resolve it?

**Comment by FoulBachelor** [comment]
All removed now, finally. <3
