### ISSUE TITLE
Updating product via API will not sync

### ISSUE THREAD

**Issue by unicoder88** [clerkio/clerk-magento2#37]
Hi!

A lot of Magento webshops receive updates via API from Product information management systems. In this case event `catalog_product_save_after` will not fire call Clerk\Clerk\Observer\ProductSaveAfterObserver , because it is declared in **adminhtml** area.

Related with https://github.com/clerkio/clerk-magento2/pull/13

Suggestions:
- easy - move even observer to global area events.xml
- proper - convert event observer into indexer

Thanks :)

P.S. Looking forward to another 2 years of silence ;)

**Comment by CasperKN** [comment]
Thanks for your feedback, we have just released this in version 4.1.9 ;)
