### ISSUE TITLE
Faceted search settings - Public or private key invalid

### ISSUE THREAD

**Issue by unicoder88** [clerkio/clerk-magento2#38]
Hi!

With latest version 4 of the module, all configuration was moved to website/store view level.
It is now impossible to set faceted settings:

https://prnt.sc/runptf

This happens because code tries to check API keys on default scope level, which is now impossible to set.

https://prnt.sc/runpdf

I suggest that maybe API keys are returned to default visibility.

Thanks!

**Comment by CasperKN** [comment]
Thanks for the issue report, it's fixed in next release

**Comment by djpaoloc** [comment]
the same error with the last version
the message is: "Public and private key must be set in order to enable faceted search" but the api keys are configured correctly
