### ISSUE TITLE
All orders are exported to Clerk, regardless of the store scope

### ISSUE THREAD

**Issue by fabianaromagnoli** [clerkio/clerk-magento2#40]
### Preconditions
* Magento 2.3.4
* clerk/magento2 v 4.0.0

### Steps to reproduce
* Magento 2 installation with two website, and one store view each, and some orders made from both it_it and eu_en stores, let's say order 1000001, 1000002 and 1000003 are made from the it_it store view, anche 2000001, 2000002 and 2000003 are made from store view eu_en.
* Create two stores on Clerk: My Store it_it and MyStore eu_en
* Set the proper sync settings on clerk:
    * This for My Site it_it:
![Screenshot 2020-05-15 at 11 34 28](https://user-images.githubusercontent.com/23638004/82037992-31596800-96a3-11ea-8ffa-65be7a913158.png)
    * and this for My Site eu_en:
![Screenshot 2020-05-15 at 11 34 45](https://user-images.githubusercontent.com/23638004/82038027-3ae2d000-96a3-11ea-8e16-f5dfd7a0aa6b.png)
* Launch sync for both My Store it_it and My Store eu_en

#### Expected behavior
I expect to see on Clerk.io only the orders of the right store scope: 1000001, 1000002 and 1000003 should have been imported only to My Store it_it, and 2000001, 2000002 and 2000003 should have been imported only to My Store eu_en.
#### Actual behavior
All orders have been exported to both Clerk stores: My Store it_it has six orders (1000001, 1000002 and 1000003, 2000001, 2000002 and 2000003), and the same happens for My Store eu_en

**Comment by CasperKN** [comment]
Thanks for the issue report, it's fixed in our next release
