### ISSUE TITLE
javascript errors cause by loading wrong version of jquery

### ISSUE THREAD

**Issue by dpotkoc** [clerkio/clerk-magento2#44]
In template file:
https://github.com/clerkio/clerk-magento2/blob/master/view/frontend/templates/livesearch.phtml#L22

you have JavaScript issue which is making conflicts with existing magento logic. You are loading wrong version of jquery from url: https://code.jquery.com/jquery-3.4.1.min.js

and you are not using require js for loading scripts.

**This is not Magento way:**

`<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', (event) => {
        ClerkSearchPage = function(){
            $("<?php echo $block->getFormSelector(); ?>").each(function (){
                $(this).attr('action', '/catalogsearch/result/');
            });
        };

        if(window.jQuery) $( document ).ready(function() { ClerkSearchPage()  });
        else{
            var script = document.createElement('script');
            document.head.appendChild(script);
            script.type = 'text/javascript';
            script.src = "https://code.jquery.com/jquery-3.4.1.min.js";
            script.integrity = "sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=";
            script.crossorigin = "anonymous";
            script.onload = ClerkSearchPage;
        }
    });
</script>`

**Comment by CasperKN** [comment]
This is fixed, in the newest version, we rewritten that part to use only plain JS ;)
