### ISSUE TITLE
Prices over 1000 are sent back from the controller as 1

### ISSUE THREAD

**Issue by WebKenth** [clerkio/clerk-magento2#48]
I am not quite sure why this controller exists as it does, it is filled with deprecated methods and is loading each product twice, once from the collection, and once with ObjectManager just to get the CreatedAt attribute ? 

https://github.com/clerkio/clerk-magento2/blob/master/Controller/Product/Index.php

Anyways, the results from this controller formats the price attribute as a string, which in turn causes the value if above 1000 to be formatted as 1 if price is between 1.000 and 1.999 and 2 if it is between 2.000 and 2.999 and so on

a temporary patch can be applied to overcome this issue where we force the product price to be returned as a float

```
Force float values since clerk requires float but formats them as strings
@package clerk/magento2
--- Controller/Product/Index.php
+++ Controller/Product/Index.php
@@ -122,6 +122,9 @@
                     $response[$key]['list_price'] = number_format((float) floatval($price) ? (float) floatval($price) : 0, 2);
                 }

+                $response[$key]['price'] = floatval($product->getPrice());
+                $response[$key]['list_price'] = floatval($product->getPrice());
+
                 $response[$key]['stock'] = $stockItem->getQty();
                 $response[$key]['product_type'] = $productType;
                 $response[$key]['created_at'] = strtotime($product->getCreatedAt());

```

**Comment by FoulBachelor** [comment]
Hi Martin,

I have just added a commit here: https://github.com/clerkio/clerk-magento2/commit/d149fd5b0c3044019c60126a492f14750881b688

This removes the created_at and product type fields from the product controller and instead handles it from the collection using field handlers.

The prices are already forced to float and number formatted in previous commit. Will close issue.
