### ISSUE TITLE
Inconsistent prices in Clerk when catalog prices are entered excluding tax, but they are displayed including taxes

### ISSUE THREAD

**Issue by fabianaromagnoli** [clerkio/clerk-magento2#49]
### Context
* clerk/magento2 v2.8.3
* Magento EE 2.2.11
* PHP 7.2
* Mysql 5.6

### Steps to reproduce
* go to Stores -> configuration -> Sales ->Taxes
* set Catalog Prices to _Excluding Tax_, like this:
![Screenshot 2021-01-26 at 15 51 32](https://user-images.githubusercontent.com/23638004/105861335-e55f1100-5fee-11eb-8fee-1e3edb69089e.png)
* in Price display Settings set Display Products Prices in Catalog to _Including Taxes_, like this:
![Screenshot 2021-01-26 at 15 53 57](https://user-images.githubusercontent.com/23638004/105861300-dd06d600-5fee-11eb-9758-d93794764357.png)
* Sync all products from Clerk, non saving products from Magento, but clicking the _Start New Data Sync_ button from clerk.io

### Expected behavior
* price and list_price in Clerk catalog should be consistent (with or without taxes, but both the same)

### Actual behavior
* price and list_price in Clerk catalog are both without taxes for simple product, list_price is without taxes for configurable products, too. But **price for configurable product is with taxes**

**Comment by kerlama** [comment]
I can confirm this too ...

**Comment by Kimpansen** [comment]
Confirmed and corrected
