### ISSUE TITLE
Undefined property on product save

### ISSUE THREAD

**Issue by friimaind** [clerkio/clerk-magento2#5]
When I save any products I receive this message:

`Notice: Undefined property: Magento\Catalog\Model\Product\Interceptor::$getData in /var/www/my_website/public_html/vendor/clerk/magento2/Observer/ProductSaveEntityAfterObserver.php on line 87`

Which refers to the fact that $productItem is empty:

`if (! isset($productItem[$field])) {
                        $productItem[$field] = $product->getData[$field];
                    }`

I could hide E_NOTICE from php.ini but I think that it would be better to fix it.

**Comment by patrick-bigbridge** [comment]
My fix for #3 was not fully implemented.

$product->getData[$field];
should be
$product->getData($field);

**Comment by friimaind** [comment]
Yes, manually changing that line fixed the warning. Can I keep the file edited while waiting for the upgrade?

**Comment by RBech** [comment]
Right again @patrick-bigbridge and thanks!

Sure thing @friimaind, will ship a new release later today implementing it

**Comment by patrick-bigbridge** [comment]
Hi Rasmus,
I hope you did not forget about the release ;)

**Comment by RBech** [comment]
@patrick-bigbridge I didn't sorry, just had a ton of stuff to do :) 2.0.1 released now fixing this
