### ISSUE TITLE
Javascript error on login, forgot password and registration pages

### ISSUE THREAD

**Issue by fabianaromagnoli** [clerkio/clerk-magento2#54]
### Description
Login, registration and forgot password pages appear to be duplicated (html of the whole page, header and footer included, is rendered twice), and there is this error in javascript console:
![clerk_error](https://user-images.githubusercontent.com/23638004/116378691-a9686180-a812-11eb-8819-5fc85c289e0f.png)

The origin of this error is in file `vendor/clerk/magento2/view/frontend/templates/powerstep_script.phtml`, line 6.

### Context

- clerk/magento2 v4.4.6
- Magento EE 2.4.2
- PHP 7.4
- Mysql 8

### Steps to reproduce

- Install module clerk/magento2 4.4.6 on Magento 2.4.2
- Navigate to login page, or registration page, or forgot password page

### Expected behaviour
The login page is correctly displayed, and there are no javascript errors in console

### Actual behaviour
The login page displayed twice (the whole page is duplicated, header and footer included) and there is this error in javascript console:

![clerk_error](https://user-images.githubusercontent.com/23638004/116377598-a1f48880-a811-11eb-98d6-63d2716f4f52.png)

**Comment by fabianaromagnoli** [comment]
I've tried on a clean installation of Magento CE 2.2.4, and I have the same behavior.

**Comment by FoulBachelor** [comment]
Hi Fabiana,

I have tested that the issue you outline continues to occur on magento 2.4.4.

I have added the XML block removals at your suggestion in this commit: https://github.com/clerkio/clerk-magento2/commit/d7629adb15e38fefc3f3926b72eaabfd37399d74

It will be included in the next release. Thank you for the detailed report and solution proposal. ❤️
