### ISSUE TITLE
Magento 2.2.0

### ISSUE THREAD

**Issue by MattFluidDigital** [clerkio/clerk-magento2#6]
This module does not allow an upgrade to Magento 2.2.0 as the dependency on the Magento Framework is for 100.1* where as Magento 2.2.0 uses the framework 101.0.*

Is there any plans to upgrade this to allow it to be used with Magento 2.2.0 versions?

**Comment by RBech** [comment]
@MattFluidDigital Definitely :) Will begin testing against 2.2.X shortly and once I'm sure everything is working as expected I'll push a new release!

**Comment by MattFluidDigital** [comment]
@RBech Brilliant, look forward to it :)

**Comment by MattFluidDigital** [comment]
@RBech has this been looked at in Magento 2.2 yet?

**Comment by RBech** [comment]
@MattFluidDigital Sorry about the delay! New release created today that should be compatible with magento 2.2
