### ISSUE TITLE
report.ERROR: Notice: Undefined index: HTTP_HOST in clerk/magento2/view/frontend/templates/tracking.phtml on line 20

### ISSUE THREAD

**Issue by ioannisgz** [clerkio/clerk-magento2#63]
Hi. It seems that in Magento 2.4.3 this line(20) in file clerk/magento2/view/frontend/templates/tracking.phtml throws error: 

`uenc: '<?php echo base64_encode((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]"); ?>',`

Error is in logs:
`report.ERROR: Notice: Undefined index: HTTP_HOST in clerk/magento2/view/frontend/templates/tracking.phtml on line 20`

Any help please?

**Comment by FoulBachelor** [comment]
Hi ioannisgz,

I have replaced the SERVER_HOST variable with SERVER_NAME since it is a more reliable indicator for the public server adress.

https://github.com/clerkio/clerk-magento2/commit/3f2ef2d0e62aca16df233c759991397a7491bcda

This will be included in the next release.
