### ISSUE TITLE
Brand attribute issue

### ISSUE THREAD

**Issue by ioannisgz** [clerkio/clerk-magento2#64]
Hi. If attribute code in magento has different name than "brand" then in Clerk brand attribute is empty for all products.
For example if brand attribute has code "manufacturer" in magento then in Clerk the brand attribute is empty and you need to add "manufacturer" as additional attribute sent to Clerk.
It should be a function in magento admin or in Clerk admin to map the sent attributes with Clerk attributes

**Comment by Kimpansen** [comment]
Hi, the "brand" is a default field from a previous version and no longer in use, it has now been revoved. 
manufacturer and all non default fields should still be added manually if they are needed.
