### ISSUE TITLE
Unexpected ')' in clerk/magento2/Model/Adapter/Product.php line 251

### ISSUE THREAD

**Issue by ioannisgz** [clerkio/clerk-magento2#68]
Hi. It seems that in your latest version you have missed in line 251:

`$price = $item->getPriceInfo()->getPrice('regular_price')->getAmount()->getValue());`

you have a wrong

>  )

at the end.

Right syntax is:

`$price = $item->getPriceInfo()->getPrice('regular_price')->getAmount()->getValue();`

**Comment by Kimpansen** [comment]
Hi this typo was corrected in later versions, thanks to you for pointing it out.
