### ISSUE TITLE
Breaks compilation

### ISSUE THREAD

**Issue by mortenbirkelund** [clerkio/clerk-magento2#71]
Magento version : 2.4.3-p1
Clerk version : 4.6.0 (Upgraded from 4.5.0)

It seems like one of the later version breaks compilations in Magento. 

```
www-data@4a2de3c9b0a4:~/public_html$ php bin/magento setup:di:compile
Compilation was started.
Interception cache generation... 6/9 [==================>---------]  66% 31 secs 476.0 MiBErrors during compilation:
	Clerk\Clerk\Model\Adapter\Product
		Extra parameters passed to parent construct: $StockStateInterface, $ProductMetadataInterface. File: /var/www/public_html/vendor/clerk/magento2/Model/Adapter/Product.php
Total Errors Count: 1

In Log.php line 92:
                            
  Error during compilation  
                            

setup:di:compile
```

Let me know if you have problems reproducing it

**Comment by rensvw** [comment]
The Product.php class in the Model/Adapter folder passes to many objects to the parent constructer (line 103).

This:

parent::__construct($scopeConfig, $eventManager, $storeManager, $collectionFactory, $Clerklogger, $StockStateInterface, $ProductMetadataInterface);

Should be this:

parent::__construct($scopeConfig, $eventManager, $storeManager, $collectionFactory, $Clerklogger);

**Comment by FoulBachelor** [comment]
Thanks for the quick feedback. I have removed the the 2 references from the constructor, as they already instantiate correctly without.

Commit: b5b38aa70d9629f4e6e40432e6e7b54644474b81

Will include in release asap, to avoid failure to upgrade.

**Comment by mortenbirkelund** [comment]
@FoulBachelor Will you also release a new version?
