### ISSUE TITLE
Powerstep popup fails on sub category

### ISSUE THREAD

**Issue by hostep** [clerkio/clerk-magento2#74]
Hey guys

Using:
- Magento OS 2.3.7
- Clerk module 4.6.1

If you have a category tree with more than one level of categories, your powerstep popup fails to show on categories which are a subcategory of another category.
That's because [the url in the ajax request](https://github.com/clerkio/clerk-magento2/blob/4.6.1/view/frontend/templates/powerstep_script.phtml#L13) is not using a urlbuilder to make it absolute, now it remains relative and causes issues.

For example, suppose I'm on the page: https://example.shop/nl/category-one and I trigger the powerstep popup, it will do an ajax call to https://example.shop/nl/clerk/powerstep/popup which is correct!
However, when you are on the page: https://example.shop/nl/category-one/category-two and trigger the powerstep popup, it will do an ajax call to https://example.shop/nl/category-one/clerk/powerstep/popup which won't work!

Suggested fix:
```diff
diff --git a/powerstep_script.phtml b/powerstep_script.phtml
index cced4b6..852a2a2 100644
--- a/powerstep_script.phtml
+++ b/powerstep_script.phtml
@@ -3,14 +3,14 @@
 if ($block->shouldShow()) :
 ?>
 <script>
-require(['jquery'], function($) {
+require(['jquery', 'mage/url'], function($, urlBuilder) {
     function getPowerstepPopup(isAjax)
     {
         $("#clerk_powerstep").remove();
         $("#clerk_powerstep .clerk-slider").remove();
         var data = isAjax ? { isAjax: true } : {};
         $.ajax({
-            url: 'clerk/powerstep/popup',
+            url: urlBuilder.build('clerk/powerstep/popup'),
             data: data,
             type: 'get',
             success: function(res) {
```

Thanks!

**Comment by FoulBachelor** [comment]
Hi Pieter,

Thanks for the detailed report and attached solution. I have pushed it to our master and it will be added to our next module release.

https://github.com/clerkio/clerk-magento2/commit/67aca34b11785a74fc7b026326c81b5f747b5dcb

**Comment by hostep** [comment]
Super, thanks @FoulBachelor!
