### ISSUE TITLE
Weird JS dependency

### ISSUE THREAD

**Issue by hostep** [clerkio/clerk-magento2#75]
Hey guys

Using:
- Magento OS 2.3.7
- Clerk module 4.6.1

We sometimes had a problem closing the powerstep popup after it was opened, this was not consistent, sometimes it worked, sometimes after a refresh or another page visit, it didn't, and so on and so forth ...

For some reason, when we removed the `'clerk'` dependency in this script: https://github.com/clerkio/clerk-magento2/blob/4.6.1/view/frontend/templates/powerstep_popup.phtml#L59, it started working 100% of the time.
I can't really explain it, I think it also has something to do with minifying of JS which is enabled on this particular shop, but I'm mostly guessing here.

I think that dependency can be removed completely, since the `Clerk` object is not used anywhere in that script block.
It did get used in the past, but that usage was removed with https://github.com/clerkio/clerk-magento2/commit/276f4899e43736f6bf87df9f28fdabb051971a97#diff-4d9bb2c884794ef6c353a9d2a1713725d0ea4668b03b2a7a5e4f1d79d92cce3f, so I'm pretty sure it's no longer needed.

Suggested fix:

```diff
diff --git a/view/frontend/templates/powerstep_popup.phtml b/view/frontend/templates/powerstep_popup.phtml
index 53e149f..21f6610 100644
--- a/view/frontend/templates/powerstep_popup.phtml
+++ b/view/frontend/templates/powerstep_popup.phtml
@@ -56,7 +56,7 @@ $categoryIds = $block->getProduct() ? $block->getProduct()->getCategoryIds() : [
     </div>
 </div>
 <script>
-require(['jquery', 'clerk'], function($, Clerk) {
+require(['jquery'], function($) {
     var popup = $("#clerk_powerstep");

     $(".clerk_powerstep_close").on("click", function() {
```

**Comment by FoulBachelor** [comment]
Loading Clerk as a dependency is the old behaviour needed when using clerk.js v1, which was a built on top of jQuery.

It is no longer needed in Clerk.js v2, which is current.

**Comment by hostep** [comment]
Nice, thanks for the quick feedback and fix (again)! 🙂
