### ISSUE TITLE
Error while compiling on Magento 2.1.x

### ISSUE THREAD

**Issue by ste80pa** [clerkio/clerk-magento2#76]
Hi 

on some old Magento2 installation you can obtain error like this while running a setup:di:compile

vendor/clerkio/magento2/Controller/Page/Index.php \Magento\Framework\ObjectManagerInterface already exists in context object

**Comment by FoulBachelor** [comment]
I believe this is solved with this merge.

https://github.com/clerkio/clerk-magento2/commit/a29bbe270a174723884ea77582df70e8c6b2bbd5

Will close issue.
