### ISSUE TITLE
Incorrect namespaces

### ISSUE THREAD

**Issue by hostep** [clerkio/clerk-magento2#78]
Hi guys

Using:
- Magento OS 2.3.7
- Clerk module 4.6.1

It looks like there are 2 incorrect namespaces in your PHP code, these can be found by dumping an optimised autoloader from composer:

```
$ composer dump-autoload -o
...
Class Clerk\Clerk\Controller\setconfig\Index located in ./vendor/clerk/magento2/Controller/Setconfig/Index.php does not comply with psr-4 autoloading standard. Skipping.
Class Clerk\Clerk\Controller\Subcriber\Index located in ./vendor/clerk/magento2/Controller/Subscriber/Index.php does not comply with psr-4 autoloading standard. Skipping.
```

1. Over [here](https://github.com/clerkio/clerk-magento2/blob/5f4648334e5678ed592f438b41da7ee4efe353f8/Controller/Setconfig/Index.php#L3), the end of the namespace should be `Setconfig` instead of `setconfig`
2. Over [here](https://github.com/clerkio/clerk-magento2/blob/5f4648334e5678ed592f438b41da7ee4efe353f8/Controller/Subscriber/Index.php#L3), the end of the namespace should be `Subscriber` instead of `Subcriber`

I haven't checked if you are using these incorrect namespaces in other classes, so please make sure you check that as well 🙂 

Also: make sure to dump a non-optimised autoloader (`composer dump-autoload`) after fixing the problems before you want to test things, because Magento can't deal very well with optimised autoloaders in developer mode.

**Comment by FoulBachelor** [comment]
Hi Pieter,

Thanks for the feedback. I just checked on my dev machine and I also only get the 2 namespace issues you list.

Both have been remedied in this commit:

https://github.com/clerkio/clerk-magento2/commit/23e8a30363130ad481aab72e6c1ca5ba03d68d69

**Comment by hostep** [comment]
Thanks!
