### ISSUE TITLE
Clerk powerstep popup creates a jquery error on my account pages

### ISSUE THREAD

**Issue by sarkadiadam** [clerkio/clerk-magento2#79]
Hello!

Enabling the **popup** mode of Clerk Powerstep breaks the my account pages (login / create accunt) with a jQuery error:

![Screenshot 2022-09-07 at 16 10 36](https://user-images.githubusercontent.com/49277901/188890649-d1a26cfa-6a5b-4236-9ff8-d08f3fb025f2.png)

![Screenshot 2022-09-07 at 16 10 51](https://user-images.githubusercontent.com/49277901/188889900-722024b7-f843-4831-af70-e85c34756656.png)

If I disable the popup option, the account pages are back to normal. 
Does this feature insert it's own jquery dependency?

Thanks,
Adam

**Comment by FoulBachelor** [comment]
This should be addressed with the following commit:

https://github.com/clerkio/clerk-magento2/commit/d7629adb15e38fefc3f3926b72eaabfd37399d74

It will be included in the coming release.
