### ISSUE TITLE
Dropdown attributes - option value instead  option id

### ISSUE THREAD

**Issue by vmalyk** [clerkio/clerk-magento2#8]
On product data sync Dropdown attributes(color, manufacturer) are synced as number and contain option_id instead option text value per store view: http://prntscr.com/h1ampx
For empty values they synced as object:  http://prntscr.com/h1an6b
For M1 version You get data more safe and use helper for that : https://github.com/clerkio/clerk-magento/blob/master/code/Helper/Data.php#L21

Reproduced on Magento 2.1.x - 2.2.x.

**Comment by RBech** [comment]
Fix coming up tommorow!

**Comment by vmalyk** [comment]
Any updates about this issue?
