### ISSUE TITLE
Single Store mode support

### ISSUE THREAD

**Issue by adamwaclawczyk** [clerkio/clerk-magento2#82]
Is there planned support for Single Store mode projects?
On projects when this options is turned on clerk module cannot be configured(mainly because Store Switcher is disabled on that kind of projects). 

The way clerk module is now coded, clerk config is not available for configuration. This is because of `showInDefault=0` https://github.com/clerkio/clerk-magento2/blame/master/etc/adminhtml/system.xml#L7

What is single store mode -> https://experienceleague.adobe.com/docs/commerce-admin/start/setup/websites-stores-views.html#single-store-mode

EDIT: I think this actually works correct

**Comment by adamwaclawczyk** [comment]
While the Store > Config > Clerk menu is visible and all items are rendered correctly, the values cannot be saved and seen after page refresh.

The actual values are saved in a different scope(`scope=websites` and `scope_id=1`, instead of default in single store projects (`scope=default` and `scope_id=0`)

Reopening since I don't think single store mode is fully supported with this issue

**Comment by FoulBachelor** [comment]
Hi Adam,

I believe you are correct, that the system.xml does not expose most settings in default. 

I think another case also needs to be put into the AbstractAction, as it currently only queries store and website.

Thanks for bringing this to my attention, I will see about making these changes.

If you have a test site, I would be happy to try an test my pre-release on it to ensure it works as intended for you. You are welcome to reach out to me on abs@clerk.io with details if this is of interest.

**Comment by adamwaclawczyk** [comment]
Thanks for the quick reply!

If that's OK with you I will test changes myself, I think I'll be able to once there's new commits in master/new feature branch

**Comment by FoulBachelor** [comment]
I can have made a Branch with my proposal, but if it has some issues on your config/site I was going to debug/test that myself to save you the trouble. 

Here is the branch with with my drafted changes. 

https://github.com/clerkio/clerk-magento2/tree/single-store

I am unsure whether this will interact correctly with retrieving facet attributes on first load. This is my main motivation for wanting to verify it on a test site of yours as well.

**Comment by adamwaclawczyk** [comment]
I made a local test using provided to me API key pair, they were saved properly along other settings I changed.

For the facet attributes, the API response: 
```
code: 200,
message: OK, 
decoded body: {"status":"ok","facets":{}}
```
Is this normal behaviour? The only thing I did was provide the API keys, save the configuration and check if the attributes are loading after site refresh. No product sync, other operations were made.

Btw we can't use composer to get the `single-store` branch - looks like [packagist repo](https://packagist.org/packages/clerk/magento2)  isn't set to auto update

**Comment by FoulBachelor** [comment]
Hi Adam,

Thanks for the quick reply. If you run a sync, with the keys plugged in from my.clerk.io the facets should populate with the available product attributes we had in the last sync.

If that works as intended for you, I would consider it solved. I just need to test that it also works with our get/set config where we can change the settigns from my.clerk.io before the release however. 

This is because we send some params for scope determination, and I am fairly certain it does not include the default case. If this is left untouched, I imagine users with access to my.clerk.io might accidentally be able to push your config to an invalid scope.

If you can confirm your attributes appear after syncing product data to the set of keys you plugged in, it would be much appreciated.

**Comment by FoulBachelor** [comment]
@adamwaclawczyk I have done a lot of testing, and some changes in the module to how scope is used for getting settings, and separated it from the scope inputs for product/collection/customer emulation.

I believe as of this commit your issue should be resolved. You are welcome to grab the master.

https://github.com/clerkio/clerk-magento2/commit/a03a9559d70e5a0cfd27e89c3e5c93809edff476

I will push a release this coming week. Thanks for your help feedbacking the issue. <3
