### ISSUE TITLE
"[API] Invalid syntax in argument: limit" In certain conditions

### ISSUE THREAD

**Issue by apomili** [clerkio/clerk-magento2#83]
When activating in the Magento 2 BO the Live Search function (and all other options I suppose), if you leave the fields in the default status (like "Number of Categories" in "don't show"), the markup in the frontend will be like

` <span class="clerk" data-template="@live-search" data-instant-search-suggestions="" data-instant-search-categories="" data-instant-search-pages="" data-instant-search-pages-type="" data-instant-search-positioning="off" data-instant-search="#search`

When typing on the input search field the console print the error "[API] Invalid syntax in argument: limit" 

To fix this error in my project I edit the livesearch template in this way, forcing to print a 0 in case of null parameter. Of course I don't know if 0 is the proper value for none in the clerk.js script but the error at least disappear.

```
<span
    class="clerk"
    data-template="@<?php echo $block->getLiveSearchTemplate(); ?>"
    data-instant-search-suggestions="<?php echo ($block->getSuggestions() ? $block->getSuggestions() : "0"); ?>"
    data-instant-search-categories="<?php echo ($block->getCategories() ? $block->getCategories() : "0"); ?>"
    data-instant-search-pages="<?php echo ($block->getPages() ? $block->getPages() : "0"); ?>"
    data-instant-search-pages-type="<?php echo $block->getPagesType(); ?>"
    data-instant-search-positioning="<?php echo $block->getDropdownPosition(); ?>"
    <?php if (empty($block->getInputSelector())) {
        echo "data-instant-search=\"#search\">";
    } else {
        echo "data-instant-search=\"".$block->getInputSelector()."\">";
    }?>

</span>
```

**Comment by FoulBachelor** [comment]
Hi Alessandro,

Thanks for the clear report, and good suggestion. I have added it in this commit and it will be included in the next release.

https://github.com/clerkio/clerk-magento2/commit/e6c0a1923fcacb85a8dd8be99469f4e9794f6f90

If you see anything else please let me know. 💌
