### ISSUE TITLE
Dependent on deletable attributes | getSource() on bool | getSource() on null

### ISSUE THREAD

**Issue by WebKenth** [clerkio/clerk-magento2#84]
The latest update causes exceptions when saving a product 

```
main.CRITICAL: Error: Call to a member function getSource() on bool in vendor/magento/module-catalog/Model/Product.php:1806
Stack trace:
#0 vendor/clerk/magento2/Model/Adapter/Product.php(494): Magento\Catalog\Model\Product->getAttributeText()
#1 vendor/clerk/magento2/Model/Adapter/AbstractAdapter.php(208): Clerk\Clerk\Model\Adapter\Product->Clerk\Clerk\Model\Adapter\{closure}()
#2 vendor/clerk/magento2/Observer/ProductSaveAfterObserver.php(174): Clerk\Clerk\Model\Adapter\AbstractAdapter->getInfoForItem()
#3 vendor/clerk/magento2/Observer/ProductSaveAfterObserver.php(111): Clerk\Clerk\Observer\ProductSaveAfterObserver->updateStore()
#4 vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Clerk\Clerk\Observer\ProductSaveAfterObserver->execute()
```

<img width="714" alt="image" src="https://user-images.githubusercontent.com/13419123/194811429-f00a9e51-67e9-4f68-9440-94a9c4535ee7.png">

https://github.com/clerkio/clerk-magento2/blob/master/Model/Adapter/Product.php#L436

These attributes can be deleted and if so the entire product creation flow is interrupted

Please program defensively when adding default attributes on products. If you request an attribute that does not exist the entity Exception will occur

**Comment by FoulBachelor** [comment]
Hi Martin,

The Manufacturer field handler is not added by default on the product, unless it is given in the settings panel, since it is not a default field.

https://github.com/clerkio/clerk-magento2/blob/master/Model/Adapter/Product.php#L484

Since the fields should be the combination of the attributes in the admin panel and settings, you got this error from having the field in the admin panel, and one of the products simply didn't have the attribute, thus causing the error?

If you could confirm it would be appreciated for guarding this error in future.

**Comment by WebKenth** [comment]
> Since the fields should be the combination of the attributes in the admin panel and settings, you got this error from having the field in the admin panel, and one of the products simply didn't have the attribute, thus causing the error?
> 
> If you could confirm it would be appreciated for guarding this error in future.

You can quickly test this by just deleting the `manufacturer` attribute from `Stores` => `Attributes` => `Product` => find `manufacturer` then delete the attribute

Then go to a product page and either create a new product or save an existing one

Since attributes are user defined you cannot expect them to be in the shop 

The default fields from https://github.com/clerkio/clerk-magento2/blob/master/Model/Adapter/Product.php#L484 are always triggered, if any of them are deleted from the shop you will get a `->getSource on null exception` due to the nature of field handlers attempting to load the attribute that does not exist, it is then parsed to a function with tries to load data on the attribute which does not exist, this causes a fatal exception

We have some custom attributes for a client:
![image](https://user-images.githubusercontent.com/13419123/195830870-f7b1d8e7-bcf5-4614-8e2d-805b21da2a6a.png)

The additional attributes load without issue, but the client deleted the manufacturer field because they prefer it to be called `maul_brand` for whatever reason

Product update/save/creation should not be halted by a module due to dependencies on default attributes which can be deleted :)

**Comment by WebKenth** [comment]
Reference image:
![image](https://user-images.githubusercontent.com/13419123/195834668-b41903a5-c105-44b3-9a01-2376bff18767.png)

**Comment by FoulBachelor** [comment]
Thanks for the quick reply Martin as well as the solution for guarding the attribute.

I will merge this into the master. Thanks for taking the time to put this together.

**Comment by Moesgaarda** [comment]
@FoulBachelor 
Please note that with the new changes to master (https://github.com/clerkio/clerk-magento2/commit/2850c6537db0755e0c0a97bb1089e4eaaf97022e) the problem still persists.

You'll need a check for whether the manifacturer attribute is set for the product before calling getAttributeText on it, and then it should be golden.

**Comment by FoulBachelor** [comment]
Hi Daniel,

Is that not gated by the return for this:
$source = $attribute->getSource();
if($source){
// ....
}
Being null, if the attribute has been removed? It should be checking whether the Resourceitem has a model for the attribute?
