### ISSUE TITLE
They renamed the composer package

### ISSUE THREAD

**Issue by JamesFX2** [clerkio/clerk-magento2#89]
If you're here because 

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires clerkio/magento2, it could not be found in any version, there may be a typo in the package name.

```

via composer update --lock

They renamed the package, it even affects versions retroactively so remove your references to clerkio/magento 

composer require clerk/magento2 4.7.0

P.S. Please can you move coding standards to require-dev. Thanks

**Comment by FoulBachelor** [comment]
Hi James,

The package name was a mismatch to our install script before. Are you unable to install after this change?

Regarding coding standards, I have moved them to require-dev as suggested.

**Comment by JamesFX2** [comment]
All is good, I was merging a conflict in composer.lock on our release branch and it was erroring because of the rename. You can close this ticket if you like, it's just there to save the next person from Googling. There's enough keywords in this thread now.

**Comment by FoulBachelor** [comment]
Hi James, appreciate the clarification. 

Will close the ticket, and thanks for taking the time to report the issue.
