### ISSUE TITLE
Extending and customization data before send to Clerk.io issue

### ISSUE THREAD

**Issue by vmalyk** [clerkio/clerk-magento2#9]
Hi!

After module review I found  some problem to add custom field based on some logic of another module. On M1 version  I found event https://github.com/clerkio/clerk-magento/blob/master/code/Model/Catalog/Product.php#L50 and It`s good point to extending. 
On M2 You use the same way as for Prestashop: 
https://help.clerk.io/using-clerk-io-on-magento-2/styling-and-design/styling-clerkio-results-to-match-your-design-on-magento-2 (some mistake in article content).

You register fieldHandlers for customize field data. In current version We can't add custom fields and register field handlers without module modification. If You add event in Index controllers to extend that or change visibility to public for using DI plugins - It`ll be easier and re-usable for implementation

**Comment by RBech** [comment]
Hi @vmalyk 
I've actually added that event on my test setup and it will be shipped with next release (hopefully later today or first thing next week)

The long term plan is to make everything much more extensible so if you find a place that could use an observer feel free to submit a pull request or open an issue :)

**Comment by vmalyk** [comment]
Hi @RBech , I hope you remember about releasing fixes ;)

**Comment by RBech** [comment]
Sould be fixed in latest commit :) Sorry for the delay, I maintain a lot of extensions and had to prioritize
